name: Atlas Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Packages
        run: |
          pip install -r requirements.txt

      - name: Run Scanner
        run: |
          python scanner.py
